# This file lists the dependencies needed to build and test all of autotag_metadata.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: autotag_metadata
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - click
  - pandas
  - pyqt>=5.12,<6
  - watchdog
  - pyyaml
  - yamllint
  - pint
  - datapackage>=1.15,<2
  - pip>=24
  - toml
  - desktop-app
