name: Build GUI exe with Pyinstaller for Windows

on:
  workflow_call:

jobs:
  build:
    name: Build autotag-metadata.exe
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.13'
        pyinstaller_ver: '==6.13'
        spec: 'autotag-metadata.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'windows-exe'
        options: --onefile, --name "Autotag-Metadata", --windowed, 
    # - name: Upload Artifact   
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: windows-exe
    #     path: dist/windows
    #     if-no-files-found: error
