name: Build GUI exe with Pyinstaller for Linux

on:
  workflow_call:

jobs:
  build:
    name: Build autotag-metadata Executable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        conda env update --quiet -n test -f environment-dev.yml
        conda list
    - name: Pyinstaller
      shell: bash -l {0}
      run: |
        pyinstaller autotag-metadata.spec
    - name: Upload Artifact   
      uses: actions/upload-artifact@v4
      with:
        name: linux-exe
        path: dist/autotag-metadata
        if-no-files-found: error
