name: Build GUI exe with Pyinstaller for Linux

on:
  workflow_call:

jobs:
  build:
    name: Build autotag-metadata Executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: prefix-dev/setup-pixi@v0.8.8
        with: { pixi-version: v0.48.0 }
      - name: Pyinstaller
        shell: pixi run bash -e {0}
        run: pixi run package
      - name: Upload Artifact   
        uses: actions/upload-artifact@v4
        with:
          name: linux-exe
          path: dist/autotag-metadata
          if-no-files-found: error
