name: Build GUI exe with Pyinstaller for Windows

on:
  workflow_call:

jobs:
  build:
    name: Build autotag-metadata.exe
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "${{ matrix.python }}"
        miniforge-variant: Mambaforge
    - name: Install PyInstaller
      shell: bash -l {0}
      run: |
        mamba env update --quiet -f environment-dev.yml -n build 
        mamba list
        mamba install -c conda-forge pyinstaller
        pyinstaller --clean -y --dist ./dist/windows --workpath tmp autotag-metadata.spec
    - name: Upload Artifact   
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: dist/windows
        if-no-files-found: error
