name: Build GUI exe with Pyinstaller for Windows

on:
  workflow_call:

jobs:
  build:
    name: Build autotag-metadata.exe
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.8
      with: { pixi-version: v0.48.0 }
    - name: Pyinstaller
      shell: pixi run bash -e {0}
      run: pixi run package
    - name: Upload Artifact   
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/autotag-metadata.exe
        if-no-files-found: error
