name: Build GUI exe with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: { submodules: recursive }
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniforge-variant: Mambaforge
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: autotag-metadata
        environment-file: environment.yml
    - name: list dependencies
      shell: bash -l {0}
      run: |
        mamba list
    - name: install autotag-metadata
      shell: bash -l {0}
      run: |
        pip install --no-dependencies .

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: autotag-metadata.spec
    - uses: actions/upload-artifact@v2
      with:
        name: autotag-metadata
        path: dist/windows
