name: Build GUI exe with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
jobs:
  build-desktop-app:
    name: Build desktop-app
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'chrisjbillington/desktop-app'

      - name: Ignore Tags
        if: github.event.ref_type != 'tag'
        run: git tag -d $(git tag --points-at HEAD)

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64

      - name: Source Distribution
        if: strategy.job-index == 0
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m build -s .

      - name: Wheel Distribution
        # Impure Linux wheels are built in the manylinux job.
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m build -w .

      - name: Upload Artifact

        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist

  build:
    name: Build autotag-metadata.exe
    runs-on: ubuntu-latest
    needs: [build-desktop-app]
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: ./dist
    - uses: actions/checkout@v3
      with: { submodules: recursive }
    # - uses: conda-incubator/setup-miniconda@v2
    #   with:
    #     python-version: "3.10"
    #     miniforge-variant: Mambaforge
    #     channels: conda-forge,defaults
    #     channel-priority: true
    #     activate-environment: autotag-metadata
    #     environment-file: environment.yml
    # - name: list dependencies
    #   shell: bash -l {0}
    #   run: |
    #     mamba list
    # - name: install autotag-metadata
    #   shell: bash -l {0}
    #   run: |
    #     pip install --no-dependencies .
    - name: debug
      run: |
        ls -la ..
    - name: Package Application
      uses: bkVBC/pyinstaller-action-windows@main
      with:
        path: .
        spec: autotag-metadata.spec
    - uses: actions/upload-artifact@v3
      with:
        name: autotag-metadata
        path: dist/windows
